# Generated by Django 5.0.4 on 2024-11-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('instructor', models.TextField()),
                ('learning_obj', models.TextField()),
                ('course_contents', models.TextField()),
                ('teaching_methods', models.TextField()),
                ('prerequisites', models.TextField()),
                ('readings', models.TextField()),
                ('applicability', models.TextField()),
                ('workload', models.TextField()),
                ('credits', models.IntegerField()),
                ('evaluation', models.TextField()),
                ('time', models.TextField()),
                ('frequency', models.TextField()),
                ('duration', models.TextField()),
                ('course_type', models.TextField()),
                ('remarks', models.TextField()),
            ],
            options={
                'db_table': 'zqm_module_en',
            },
        ),
    ]
