# Generated by Django 5.0.4 on 2024-11-07 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'managed': False},
        ),
    ]
